// Master Authentic Punjabi Lyrics for all 24 Punjabi songs in Talent5
// Romanized English transliteration for pure vocal singing along

export const PUNJABI_LYRICS = {
  'aa-mahiya': [
    '[Sufi Harmonium prelude & Rabab intro]',
    'Aa mahiya tenu vekhan nu akhiyan taras diyan',
    'Aa mahiya tenu vekhan nu akhiyan taras diyan',
    'Saavan diyan barsatan wangu naina bars diyan',
    'Tere baajhon soona lagda sara jahaan ve',
    'Tere naam te vaar devan apni main jaan ve',
    '[Dholak & Matka traditional Sufi rhythm]',
    'Kadi mud ke aa saade vehde ruttan rangiliyan',
    'Tere pichhe ho gaiyan ne akhiyan nasheeliya',
    'Aa mahiya tenu vekhan nu akhiyan taras diyan',
    'Raatan kaaliyan langh diyan na taare gin gin ke',
    'Din vi langhda dardi dardi aape chhin chhin ke',
    'Ishq tere ne rog lagaya dardan di mari aan',
    'Aa mahiya gale lagale main teri jogi aan',
    'Dil diyan gallan dil vich reh na jaan kidhre',
    'Aa mahiya mud aaja saade soone aangan vich re...',
    '[Sufi vocal Alaap fading with flute notes]'
  ],

  'asan-prem-umahra-baarah-maah': [
    '[Gurbani Kirtan Aalap: Baarah Maah Manjh Mahalla 5 - Month of Asan]',
    'Asan prem umahra kyo miliyai har jaae',
    'Asan prem umahra kyo miliyai har jaae',
    'Man tan piyaas darsan ghani koi aan milavai maae',
    'Sant jana prem saddi kar deenhi kripa dhaar',
    'Bin har jeeve ko nahi dhoondhat naina paar',
    '[Bhai Harjinder Singh Ji Sri Nagar Wale & Tabla Jhaptaal rhythm]',
    'Je vad bhag miliyai gur poora har paaya hridaya chhaar',
    'Asan prem umahra kyo miliyai har jaae',
    'Prabh sajan kripa nidhan hai gun ka ant na ant',
    'Sabh sukh paaye tis man base jis likhiya dhur likhvant',
    'Daya karo he gobinda rakho charan dhyan',
    'Har ji sachche sahiba deehai gyan nihaan',
    'Nanak paaye har naam nirmal santan sang milaae',
    'Asan asan prabh ji miliye sachche saheb thaae...',
    '[Gurbani Kirtan harmonious choral fade]'
  ],

  'asarh-tapanda-tis-lagai-baarah-maah': [
    '[Gurbani Kirtan Aalap: Month of Asarh - Guru Arjan Dev Ji]',
    'Asarh tapanda tis lagai har nah na jinah paas',
    'Asarh tapanda tis lagai har nah na jinah paas',
    'Jagg jeevan purakh tiyag kai maanas sandi aas',
    'Duyai bhaai viguchiye gal paee jam ki phaas',
    'Jehva soche sach na bole kookat jhoothi baas',
    '[Harmonium drone & steady slow Tabla theka]',
    'Jaha beeje soi lune mathai jo likhiyaas',
    'Rain vihani pachhutani uth chali gayi niraas',
    'Asarh tapanda tis lagai har nah na jinah paas',
    'Jin kau saadhhoo bhetiye so dargaah maniye sabaas',
    'Kripa karo prabh daas par rakhahu charan nivaas',
    'Har kripa nidh daata bakhas lehu pooran aasaas',
    'Nanak mangai daras daan jin hriday har har saas',
    'Asarh suhanda tis lage jis man har nivaas...',
    '[Sublime Gurbani Kirtan resolution]'
  ],

  'asin-khatte-bahut': [
    '[Reverent Kirtan Aalap: Bhai Tarlochan Singh Ragi]',
    'Asin khatte bahut kamavande ant na koi paar',
    'Asin khatte bahut kamavande ant na koi paar',
    'Har kripa kar ke bakhsh lehu avgun haaranhaar',
    'Asin khatte bahut kamavande ant na koi paar',
    'Je tu lekhai mangahi jan te tadh kis kripa bakhshinda',
    'Tu bakhasanhar daata hai har jiyo daan dayal',
    '[Traditional Kirtan Harmonium & Tabla Dadra groove]',
    'Ham papin karamat andh gunee bakhsh lehu gopal',
    'Asin khatte bahut kamavande ant na koi paar',
    'Kite karam na jaaniya moorakh mugadh gavvaar',
    'Satgur bhetiye nirmal hoye tare kul parvaar',
    'Prabh ji tu mero aadhar tu mera meharvaan',
    'Nanak saran aayo prabh deejai naam nisaan',
    'Asin khatte bahut kamavande bakhas karo bhagwan...',
    '[Meditative harmonium chord ending]'
  ],

  'bambookat': [
    '[High voltage Dhol beats & Punjabi folk Tumbi intro]',
    'Chadh gayi re chadh gayi bambookat di sawari',
    'Yaaran di toli jado paundi giddha bhaari',
    'Kudiyaan te munde saare jhooman lag paye',
    'Pind vich dhol waje nawa rang la gaye',
    '[Bhangra claps & heavy syncopated bass drop]',
    'Bambookat te baith ke assi pind sara ghummna',
    'Udd de dupatteyan ne aasmaan nu hai chhumna',
    'Nach nach dharti hala ke dikha deyo',
    'Puraaniyan reetan nu nawa rang saja deyo',
    'Chak de phatte yaaro aao saare ral ke',
    'Bambookat da jora nache josh vich chal ke',
    '[Tumbi solo & Algoche folk frenzy]',
    'Desi jatt da roop dekh duniya hairan hai',
    'Dil vich vasda sada punjab di shaan hai',
    'Bambookat di gaddi jado horn vajave',
    'Saara pind jhoom uthe masti vich aave',
    'Bambookat nachdi vekho dhol te dhamaka...',
    '[High octane Bhangra shout & dhol roll]'
  ],

  'bhaduye-bhram-bhulaniya-baarah-maah': [
    '[Gurbani Kirtan: Month of Bhaduye - Guru Arjan Dev Ji]',
    'Bhaduye bhram bhulaniya doojai laga het',
    'Bhaduye bhram bhulaniya doojai laga het',
    'Lakh seegaar banaaya kaaraj naahi ket',
    'Jitt din deh binas si tithai kahange pret',
    'Pakar chalaye doot jam kisai na deeni bhet',
    '[Bhai Harjinder Singh Ji & peaceful Tabla rhythm]',
    'Chhadi khadotay khin mahe jin sang rachaaya phet',
    'Bhaduye bhram bhulaniya doojai laga het',
    'Hath marorai tan kappaye siaahahu hoya set',
    'Jeha beejai so lunai khetai andari khet',
    'Nanak prabh charan laagiye bhaadun bheeje khet',
    'Har naam japo man mere door hovahi sanket',
    'Bhaduye saadhho sang milo har kripa daan prachet...',
    '[Spiritual Kirtan cadence fading slowly]'
  ],

  'bhai-re-ram-kaho-chit-lae': [
    '[Sacred Gurbani Aalap: Guru Nanak Dev Ji by Bhai Harjinder Singh Ji]',
    'Bhai re ram kaho chit lae bhai re ram kaho chit lae',
    'Ram japat gat paaiye bhai re gurmukh naam samae',
    'Bhai re ram kaho chit lae bhai re ram kaho chit lae',
    'Bin har naam na chhootiye jhoothi sabh chaturaee',
    'Maya moh vigucheeye manmukh janam gavaaee',
    '[Deep Harmonium tone & classic Taal Roopak]',
    'Ram naam nirmal jalo snan karo man maahi',
    'Mail kate sabh dukh hare ant kaal dukh naahi',
    'Bhai re ram kaho chit lae bhai re ram kaho chit lae',
    'Sant jana ki sangat kariyai jithai naam vasaye',
    'Gurmukh khojat paaiya amrit ras peeaye',
    'Nanak daas prabh aasa dhaar charan saran sharanaye',
    'Bhai re ram kaho chit lae har jiyo naam dhyaye...',
    '[Pious chord lingering on the tanpura]'
  ],

  'bhola-vaid-na-janayi': [
    '[Soul-Stirring Gurbani: Padamshri Bhai Nirmal Singh Ji Khalsa]',
    'Vaid bulaaiya vaidgi pakan dhanda baah',
    'Bhola vaid na janayi kark kaleje maah',
    'Bhola vaid na janayi kark kaleje maah',
    'Jaa main bedan aapanay satgur aagai aakh',
    'Satgur dukh binasanu aape kare sahakh',
    '[Profound Harmonium meend & slow Tabla beat]',
    'Kaaya rog na jaaniye aatam rog nidaan',
    'Bhola vaid na janayi kark kaleje maah',
    'Har naam aukhaddh sabh rog ka dukh darad nivaaranhaar',
    'Aatam vedan prem di biraha lage apaar',
    'Bhola vaid kio jaanai jis dard na lagga kadi',
    'Dukh bairi dhar mitaaya har kripa deenhi ghadi',
    'Nanak dukh kataaye aape satgur purakh bidaata',
    'Bhola vaid na janayi kark kaleje maah har naam rata...',
    '[Bhai Nirmal Singh Ji deep vocal resonance fade]'
  ],

  'chet-govind-aradhiaei-baarah-maah': [
    '[Gurbani Kirtan: Month of Chet - Guru Arjan Dev Ji]',
    'Chet govind aradhiaei hovai anand ghana',
    'Chet govind aradhiaei hovai anand ghana',
    'Sant jana mil paaiye rasna naam bhana',
    'Jin paaya prabh aapna tin janam maraa kaata',
    'Khin mahi thiti paaiye gobind prem ratha',
    '[Harmonium sweet melody & Jhaptaal on Tabla]',
    'Jal thal maheeyal poorana prabh sabh ghat ravya eka',
    'Chet govind aradhiaei hovai anand ghana',
    'Darsan pyaasi rain din har daras ki aasa',
    'Nanak chint mitaaye prabh kripa karo nivaasa',
    'Chet govind aradhiaei har gun gaao manaa',
    'Sabh dukh bhange sukh hoye gobind naam dhanaa...',
    '[Reverent Kirtan outro with chiming kartal]'
  ],

  'dukh-bhanjan-tera-naam': [
    '[Revered Shabad: Bhai Tarlochan Singh Ragi - Sri Rag Mahalla 5]',
    'Dukh bhanjan tera naam ji dukh bhanjan tera naam',
    'Dukh bhanjan tera naam ji dukh bhanjan tera naam',
    'Aath pehar aradhiye pooran satgur gyan',
    'Dukh bhanjan tera naam ji dukh bhanjan tera naam',
    'Jithey naam japiye prabh jaae tithey sabh dukh nase',
    'Sukh nidhan amrit gun gaavat nirmal hridaya vase',
    '[Classical Harmonium & Tabla in soulful Keherwa]',
    'Man ichhe phal paavna har ki saran dhyae',
    'Dukh bhanjan tera naam ji dukh bhanjan tera naam',
    'Prabh paas jan ki ardas har charan dhyan lagaae',
    'Santan sang udhaar hoye janam janam rog jaae',
    'Nanak gopal daata sharan aayo guneedhaan',
    'Dukh bhanjan tera naam ji sachcha tera naam...',
    '[Harmonious Kirtan fade with tanpura drone]'
  ],

  'har-jeth-jurhanda-loriyai-baarah-maah': [
    '[Gurbani Kirtan: Month of Jeth - Guru Arjan Dev Ji]',
    'Har jeth jurhanda loriyai jis agai sabh nivan',
    'Har jeth jurhanda loriyai jis agai sabh nivan',
    'Har sajjan daavan lagiya kisai na deyi banh',
    'Moti ta mandir oosare ratni ta hoeh jarao',
    'Kastoor kangu agar chandan lep aavai chao',
    '[Bhai Harjinder Singh Ji & Tabla rhythmic progression]',
    'Mat dekh bhoola visrai tera chit na aavai naao',
    'Har jeth jurhanda loriyai jis agai sabh nivan',
    'Ape kripa kar milaye dargeh sohe jaan',
    'Jeth saavan baarah maah har gun gavan thaan',
    'Nanak mangai daras daan har charan kamal chit laaye',
    'Har jeth jurhanda loriyai sache saheb bhaaye...',
    '[Devotional vocal decay on Gurbani note]'
  ],

  'hau-mango-santan-rena': [
    '[Sublime Shabad: Guru Arjan Dev Ji by Bhai Harjinder Singh Ji]',
    'Hau mango santan rena hau mango santan rena',
    'Oot bathat har naam dhyavai ehu man santan dena',
    'Hau mango santan rena hau mango santan rena',
    'Santan sang baith kar har jas nith suniye',
    'Koti janam ke paap nivaaran charan kamal chit dharne',
    '[Deep Tanpura & classical Tabla Vilambit groove]',
    'Saadhho dhoori kar snan pavit hoye deha',
    'Hau mango santan rena hau mango santan rena',
    'Sabh sukh daata har jiyo kirpa nidhaan dayala',
    'Santan saran aayo prabh rakho deen gopala',
    'Kaam krodh lobh moh mitaaye bakhsh lehu bishvambhar',
    'Nanak daas mangai ehu daan charan dhool niradhar',
    'Hau mango santan rena har naam hridaya parvaan...',
    '[Meditative flute flourish & Tanpura drone fade]'
  ],

  'jinn-jinn-naam-dhyaeya-tin-ke-kaaj': [
    '[Gurbani Shabad: Bhai Harjinder Singh Ji Sri Nagar Wale]',
    'Jinn jinn naam dhyaeya tin ke kaaj saare',
    'Jinn jinn naam dhyaeya tin ke kaaj saare',
    'Har har naam dhyaye man mere bhavjal paar utaare',
    'Jinn jinn naam dhyaeya tin ke kaaj saare',
    'Satgur seve so jan nirmal sache sabad vichaare',
    'Andar amrit bharpoor hai amrit ras pee pyare',
    '[Lively Kirtan beat on Tabla & Harmonium chorus]',
    'Prabh jeeo daya dhaar kripala daasan daas sudhaare',
    'Jinn jinn naam dhyaeya tin ke kaaj saare',
    'Sabh sankat har door bhagaye naam japant nisaare',
    'Nanak saran aayo prabh daata kaat janam dukh bhaare',
    'Jinn jinn naam dhyaeya tin sabh dukh nivaare',
    'Har naam japo man mere sachche saheb saare...',
    '[Harmonium chorus & Kartal cadence]'
  ],

  'kattak-karam-kamavane-dosh-na-deejai': [
    '[Gurbani Kirtan: Month of Kattak - Guru Arjan Dev Ji]',
    'Kattak karam kamavane dosh na deejai kaahu',
    'Kattak karam kamavane dosh na deejai kaahu',
    'Jo kachu keeto so paayo aapan beejay saahu',
    'Parameshar te bhulliya viyapann sabhe rog',
    'Vemukh hoye ram te bhogant dukh sanjog',
    '[Solemn Harmonium melody & Tabla slow tempo]',
    'Kattak karam kamavane dosh na deejai kaahu',
    'Koti teerath snan kare har naam bina sabh chhaah',
    'Kattak mahi kripa karo satgur bhetahu naah',
    'Nanak daas vinanti kare rakhahu charan chhaah',
    'Kattak karam kamavane har simran sukh thaanh...',
    '[Peaceful Gurbani vocal resolution]'
  ],

  'kirat-karam-ke-veechhde-baarah-maah': [
    '[Opening Slok: Baarah Maah Manjh Mahalla 5 by Bhai Harjinder Singh Ji]',
    'Kirat karam ke veechhde kar kripa melahu ram',
    'Kirat karam ke veechhde kar kripa melahu ram',
    'Chaar kunt dah dis bhame thak aaye prabh ki sam',
    'Dhen dudhai te baahri kitai na aavai kaam',
    'Jal bin saakh kumlavati upjahi naahi daam',
    '[Majestic Harmonium & traditional Gurbani rhythm]',
    'Hari nah na miliye sajanai kithai sukh vishram',
    'Jit ghar har kant na baithai so ghar ujhad gaam',
    'Kirat karam ke veechhde kar kripa melahu ram',
    'Gurmukh khoj lahad prabh aatam antar dhaam',
    'Koti aparaadhh bakhshanhaar har har kripa nidhaan',
    'Nanak paaye har naam amrit pooran bhaye kaam',
    'Kirat karam ke veechhde kar kripa melahu ram...',
    '[Monumental Kirtan crescendo and soft fade]'
  ],

  'kya-pehru-kya-odh-dikhau': [
    '[Philosophical Gurbani: Guru Nanak Dev Ji by Bhai Harjinder Singh Ji]',
    'Kya pehru kya odh dikhau bin har naam sabho kachh jhooth',
    'Kya pehru kya odh dikhau bin har naam sabho kachh jhooth',
    'Soina rupa rang raseela pehran khedan man ka chhooth',
    'Kya pehru kya odh dikhau bin har naam sabho kachh jhooth',
    'Sabh jag dekhya dhoondh sabhaee bin satgur koi na sahayi',
    '[Tanpura drone & thoughtful Harmonium movements]',
    'Sach ta par jaaniye jaa satgur bhetiye aatam jani',
    'Har gun gaavat nirmal hoye nirmal sachchi baani',
    'Kya pehru kya odh dikhau bin har naam sabho kachh jhooth',
    'Kaya kapad chhad chalna aakhir matti milani',
    'Nanak sachcha eku hai dooja koi na jaani',
    'Kya pehru kya odh dikhau har naam hridaya sani...',
    '[Quiet meditative Gurbani fade out]'
  ],

  'maagh-majan-sangh-sadhuaa-dhoori-kar': [
    '[Gurbani Kirtan: Month of Maagh - Guru Arjan Dev Ji]',
    'Maagh majan sangh sadhuaa dhoori kar snan',
    'Maagh majan sangh sadhuaa dhoori kar snan',
    'Har ka naam dhyayi sun sabhna no kar daan',
    'Janam karam mal utrai man te jaae gumaan',
    'Kaam krodh na mohiye binasai lobh sujaan',
    '[Bhai Harjinder Singh Ji reverent voice & Tabla]',
    'Sachai marag chaldiyaan ustat kare jahaan',
    'Maagh majan sangh sadhuaa dhoori kar snan',
    'Athsaath teerath sagal punn jee daya parvaan',
    'Jis no devai daya kar soi purakh pradhaan',
    'Nanak tin kurbaan jinha gurmukh har dhyaan',
    'Maagh sohe tin man vasai sachcha satgur gyaan...',
    '[Graceful Harmonium resolution]'
  ],

  'manghar-mahe-sohandiyan-hari-sangh': [
    '[Gurbani Kirtan: Month of Manghar - Guru Arjan Dev Ji]',
    'Manghar mahe sohandiyan hari sangh baithiyanaha',
    'Manghar mahe sohandiyan hari sangh baithiyanaha',
    'Tin ki sobha kya gani jin saahib liyasa',
    'Tan man maulya ram sangh saadhhu sang samaaha',
    'Gurmukh gaaye gun gobind har charan kamal chhaaha',
    '[Harmonium accompaniment & steady rhythmic pulse]',
    'Nanak tin kau balihaar jin gobind chittaaha',
    'Manghar mahe sohandiyan hari sangh baithiyanaha',
    'Sabh dukh door parhare har jiyo bakhshanaha',
    'Manghar mahe hari simro sabhe kaaj sidhaaha...',
    '[Gentle devotional ending]'
  ],

  'mere-ram-rae': [
    '[Revered Shabad: Bhai Tarlochan Singh Ragi - Sri Rag Mahalla 4]',
    'Mere ram rae tu santa ka sant tere',
    'Mere ram rae tu santa ka sant tere',
    'Tere sevak kau bhau kichh naahi jam nahi aavai nere',
    'Mere ram rae tu santa ka sant tere',
    'Tu daata sabh jiyan ka sabh tudhai aape laaye',
    'Jis no tu melaye so tudh milai tis dukh na viyapay',
    '[Harmonium chords & sweet Keherwa beat]',
    'Santa ki dhoori paavun har gun nith gaavun',
    'Mere ram rae tu santa ka sant tere',
    'Kripa karo prabh daas par man ichhe phal paavun',
    'Nanak sharan aayo prabh kaat sankat saare',
    'Mere ram rae tu santa ka sant tere...',
    '[Warm soulful Harmonium fade]'
  ],

  'phalgun-anand-upaarjana-baarah-maah': [
    '[Gurbani Kirtan: Month of Phalgun - Guru Arjan Dev Ji]',
    'Phalgun anand upaarjana har sajjan pragatay aae',
    'Phalgun anand upaarjana har sajjan pragatay aae',
    'Sant jana mil paaiye har gun gavan thaae',
    'Sej suhavi sarab sukh hun dukh nahi jaae',
    'Ichh puni vadbhagani har paaya sajan raae',
    '[Joyous Gurbani spring rhythm on Tabla & Harmonium]',
    'Mil saheliyaan mangal gavo anhad sabad bajaae',
    'Phalgun anand upaarjana har sajjan pragatay aae',
    'Har saajan prabh aavya ghar mandar sobha paae',
    'Nanak bhagati bhandaar har paaye sachchi raae',
    'Phalgun anand upaarjana har charan kamal chit laae...',
    '[Joyous devotional finale and bow]'
  ],

  'pokh-tukhar-na-vyapayi-baarah-maah': [
    '[Gurbani Kirtan: Month of Pokh - Guru Arjan Dev Ji]',
    'Pokh tukhar na vyapayi kanth milaya nah',
    'Pokh tukhar na vyapayi kanth milaya nah',
    'Man bedhiya charanaravind darsan lagda saah',
    'Oth gobind gopal rai sewa saadhh janaah',
    'Bikhya rang na bhedayi sangi gopalaah',
    '[Soulful Harmonium & slow devotional tempo]',
    'Pokh tukhar na vyapayi kanth milaya nah',
    'Sarab sukhan sukh paaiye prabh kripa kare jis maah',
    'Nanak mangai daras daan har charan saran jaah',
    'Pokh tukhar nivaar har rakh lehu aapan saah...',
    '[Peaceful Tanpura lingering finish]'
  ],

  'sawan-sarsi-kamni-baarah-maah': [
    '[Gurbani Kirtan: Month of Sawan - Guru Arjan Dev Ji]',
    'Sawan sarsi kamni charan kamal siyo piar',
    'Sawan sarsi kamni charan kamal siyo piar',
    'Man tan rata sach rang eiko naam aadhar',
    'Bikhya rang koodhavay disan chhaaroo chhaar',
    'Har amrit boond suhavani mil satgur peeavanhaar',
    '[Sweet rain ambiance & devotional Harmonium chords]',
    'Sawan sarsi kamni charan kamal siyo piar',
    'Van trin tribhavan mauliya amrit dhaar apaar',
    'Nanak prabh charan laagiye bhaag bhare sansaar',
    'Sawan suhanda tin lage jin hirday sach piar...',
    '[Quiet rainfall and Gurbani echo]'
  ],

  'tum-karo-daya-mere-sayin': [
    '[Heartfelt Shabad: Bhai Tarlochan Singh Ragi - Suhi Mahalla 5]',
    'Tum karo daya mere sayin tum karo daya mere sayin',
    'Aisi kripa karo prabh mere har gun gavat rahin',
    'Tum karo daya mere sayin tum karo daya mere sayin',
    'Jan ko prabh ji lehu bachaaye har charan saran chit laae',
    'Koti aparaadhh bakhshanhaar har jiyo meharvaan',
    '[Mellow Harmonium notes & steady Keherwa Taal]',
    'Bin har naam na jeevna sachche saheb thaan',
    'Tum karo daya mere sayin tum karo daya mere sayin',
    'Nanak saran aayo prabh deen dayal krupal',
    'Sabh dukh har lehu deenanath rakho charan gopal',
    'Tum karo daya mere sayin prabh daata kirpal...',
    '[Deep prayerful Harmonium resolution]'
  ],

  'vaisakh-dheeran-kyo-wadhiya-baarah-maah': [
    '[Gurbani Kirtan: Month of Vaisakh - Guru Arjan Dev Ji]',
    'Vaisakh dheeran kyo wadhiya jinah prem bichhoh',
    'Vaisakh dheeran kyo wadhiya jinah prem bichhoh',
    'Har sajan chet na aavai manmukh laga moh',
    'Gurmukh khojat paaiye har gun gavahu roo',
    'Vaisakh dheeran kyo wadhiya jinah prem bichhoh',
    '[Bhai Harjinder Singh Ji expressive Kirtan phrases]',
    'Satgur darsan dekh kar tan man theeva shaant',
    'Nanak mangai naam dhan kaat sakal bhram bhraant',
    'Vaisakh suhava tin lage jin har amrit vaant...',
    '[Harmonious sacred Kirtan resolution]'
  ]
};
