// Master Authentic Hindi Lyrics for all 29 Hindi songs in Talent5
// Romanized English transliteration for pure vocal singing along

export const HINDI_LYRICS = {
  'aao-to-sahi-mohan-mere-tarasingh': [
    '[Devotional Alaap: Tarasingh Dodve Nirgun Santvani tradition]',
    'Aao to sahi mohan mere aao to sahi mohan mere',
    'Aao to sahi girdhar pyare aao to sahi mohan mere',
    'Palak bichhaaye baate johun biraha agan tan taape',
    'Aao to sahi kanha pyare de darshan banwari',
    'Gokul dhoondha mathura dhoondha dhoondha vrindavan saara',
    '[Bansuri & Dholak interlude rhythm]',
    'Yamuna ke teere kadam ki chhaiyan dhoondhe naina baawre',
    'Nand ke nandan bansi wale mor mukut pitambardhari',
    'Mori binati suno ghanshyam he brijraj bihari',
    'Tum bin kaun sunega hamari araj garib nawaj',
    'Aao to sahi mohan mere aao to sahi mohan mere',
    'Meera kahe prabhu girdhar nagar charan kamal chit laayo',
    'Janam maran ka dukh har leejai de darshan sukhdayi',
    'Aao to sahi mohan mere pyare girdhari lala',
    'Har dam simrun naam tiharo mohan bansi wale',
    'Aao to sahi mohan mere aao to sahi girdhari re...',
    '[Devotional Dholak & Kartal finale fading gracefully]'
  ],

  'baarish': [
    '[Acoustic Guitar prelude & rain drop ambiance]',
    'Bheegi bheegi hawayein kehne lagi hain dastaan',
    'Baras rahi hai yaadon ki baarish khula hai aasmaan',
    'Boondon mein dhoondhoon tere nishan har mod par',
    'Kyun chhoo ke guzre ye thandi hawa dil tod kar',
    '[Electric Guitar riff & soulful melody cadence]',
    'Baarish ki dhun pe gaata hai mann geet purane',
    'Beete lamhon ke saaye lage hain aane jaane',
    'Har boond mein chhupi hai teri hi ek sada',
    'Tu paas nahi phir bhi kaisa hai ye nasha',
    'Bheegi bheegi raaton mein aisi bekarari hai',
    'Teri meethi baaton ki ab bhi khumari hai',
    '[Solo Guitar flourish & percussion groove]',
    'Barsaat le aayi phir se teri nigahein',
    'Kab se takti hain tanha ye sooni raahein',
    'Aaja re baadal ban ke baras ja mere dil pe',
    'Mita de faasle jo hain dono ke darmiyan',
    'Baarish ke iss mausam mein sang tera ho meherban...',
    '[Soft acoustic acoustic cadence fading with rain]'
  ],

  'baras-jaye': [
    '[Indie synth pad & gentle percussion intro]',
    'Baras jaye re baras jaye badariya re',
    'Sookhe dil ki zameen pe aake thehar jaye re',
    'Khamosh raste dhundhli fizayein kehti hain',
    'Teri hi baatein meri saanson mein behti hain',
    'Baras jaye re baadal ban ke baras jaye',
    '[Melodic bassline & acoustic strums]',
    'Umeedon ke jugnu jagmagaye andheri raat mein',
    'Kaisa jaadu ghula hai saawan ki har baat mein',
    'Baras jaye megha mita de tishna-e-dil',
    'Chalte chalte mil jaye manzil se manzil',
    'Dhoop chhaon ka khel ye kaisa ajeeb hai',
    'Tu door ho ke bhi lagta kareeb hai',
    '[Synthesizer sweep & atmospheric vocal echoes]',
    'Boond boond barsat mein bheege mera aalam',
    'Tere bina adhoora tha har ek mausam',
    'Ab jo barse to tham na sake ye silsila',
    'Mita de zamaane ke diye har ek gila',
    'Baras jaye re pyari badariya baras jaye re...',
    '[Gentle ambient chime outro]'
  ],

  'baso-more-nayan-mein-nandlal-mss': [
    '[Tanpura Aalap: Bharat Ratna M. S. Subbulakshmi devotional majesty]',
    'Baso more nayan mein nandlal baso more nayan mein nandlal',
    'Baso more nayan mein nandlal baso more nayan mein nandlal',
    'Mohani murati sanwari surati naina bane bishal',
    'Baso more nayan mein nandlal baso more nayan mein nandlal',
    'Adhar sudha ras murali virajai ur baijanti maal',
    'Mohani murati sanwari surati naina bane bishal',
    '[Veena & Mridangam devotional Gamaka cadence]',
    'Chhudra ghantika kati tat sobhit nupur sabad rasal',
    'Baso more nayan mein nandlal baso more nayan mein nandlal',
    'Meera prabhu santan sukhdayi bhagat bachhal gopal',
    'Meera kahe prabhu giridhar nagara charan kamal chit laayo',
    'Baso more nayan mein nandlal shree nandlal gopal',
    'Kripa karo he brij ke basi kaato sakal janjal',
    'Baso more nayan mein nandlal baso more nayan mein nandlal',
    'Syam sundar madan mohan murali dhar gopal',
    'Baso more nayan mein nandlal prabhu girdhar nandlal...',
    '[Devotional Veena finale & meditative chord]'
  ],

  'bhaagam-bhaag': [
    '[Funky bass slap & driving drum beat intro]',
    'Bhaagam bhaag machi hai re zamaane mein har su',
    'Kisko furasat hai yaaron dhoondhe dil ka sukoon',
    'Ruk ja thahar ja do pal jee le muskura kar',
    'Zindagi ke rangeen palon ko gale laga kar',
    '[Brass section hits & syncopated funk rhythm]',
    'Ghar se nikle daude subah shaam daude',
    'Khwabon ke peeche bheed mein sab naate tode',
    'Arey ruk re musafir thoda sa saans le le',
    'Apne dil ki dhadkan ki pyari aawaz sun le',
    'Bhaagam bhaag chhod ke thoda jhoom le',
    'Khushiyon bhare iss aasmaan ko choom le',
    '[Guitar solo break with high-energy beats]',
    'Paison ki daud mein kho na dena apna aalam',
    'Kal ki fikar chhod ke jeena seekh le har dam',
    'Bhaagam bhaag ki duniya mein pyaar hi sach hai',
    'Hans ke bitaana hi jeene ka asli raaz hai',
    'Bhaagam bhaag se aage badh ke mast ho ja...',
    '[Upbeat brass punch & laughter fade]'
  ],

  'chakar-rakhoji-mhare-girdhari-lala-mss': [
    '[Bhakti Alaap: M. S. Subbulakshmi singing Sant Meera Bai]',
    'Chakar rakhoji mhare girdhari lala chakar rakhoji',
    'Chakar rakhoji mhare girdhari lala chakar rakhoji',
    'Chakar rahsyun baag lagaasyun nit uth darsan paasyun',
    'Chakar rakhoji mhare girdhari lala chakar rakhoji',
    'Brundaban ki kunj galin mein gobind leela gaasyun',
    'Chakari mein darsan paasyun sumiran paasyun kharchi',
    '[Harmonium & Tanpura classical sanchara]',
    'Bhaav bhagati jaagiri paasyun teenu baata sarsyun',
    'Chakar rakhoji mhare girdhari lala chakar rakhoji',
    'Mor mukut peetambar sohe gal baijanti maala',
    'Brundaban mein dhenu charaave mohan murali waala',
    'Chakar rakhoji mhare girdhari lala girdhari lala',
    'Hari unche unche mahal banaavun bich bich raakhun baari',
    'Kusumbi saadi saji sajan milvaan kanku chhaanti pyaari',
    'Meera ke prabhu gahir gambhira hriday raho ji dheera',
    'Aadhi raat prabhu darsan deenho prem nadiji ke teera',
    'Chakar rakhoji mhare girdhari lala chakar rakhoji...',
    '[Subbulakshmi meditative bhajan finale]'
  ],

  'daras-bina-dukhan-laage-nain-mss': [
    '[Vilambit Aalap: M. S. Subbulakshmi in pure Raga Bhairavi]',
    'Daras bina dukhan laage nain daras bina dukhan laage nain',
    'Daras bina dukhan laage nain girdhari pyaare pyare',
    'Jabte tum bichhude prabhu more kabahu na paayo chain',
    'Daras bina dukhan laage nain daras bina dukhan laage nain',
    'Sabad sunat meri chhatiyan kaanpe meetho laage bain',
    'Daras bina dukhan laage nain mohan pyaare nandlal',
    '[Veena meend & soothing tanpura resonance]',
    'Biraha katha kahu kason sajani bahat naina din rain',
    'Daras bina dukhan laage nain banwari bansi wale',
    'Meera ke prabhu kab re miloge dukh bhanjan sukh den',
    'Aao re kanhaiya pyaare aao mohan mero dhyan dharain',
    'Charan kamal ki aash lagayi din beete bina chain',
    'Daras bina dukhan laage nain daras bina dukhan laage nain',
    'Tum bin kaun haro mero sankat deen dayal krupal',
    'Daras bina dukhan laage nain daras bina dukhan laage nain',
    'Meera prabhu girdhar nagar aao mohan nath...',
    '[Raga Bhairavi final devotion cadence]'
  ],

  'deep-love': [
    '[Chill electronic synth chords & slow hip-hop beat]',
    'In your eyes I see the ocean deep inside my heart',
    'Gehra pyaar tera saanson mein basa hai har ghadi',
    'Tujhse shuru meri duniya tujhpe hi thehari zameen',
    'Deep love so real it makes me feel alive again',
    '[Groovy 808 bass & vocal chops]',
    'Har lamha tera zikr meri baton mein shaamil hai',
    'Tu jo mil gaya to lagta hai jahaan haasil hai',
    'Raahon mein bikhre sitaare ban gaye tere kadam',
    'Mita diye faasle jo the humare darmiyan har dum',
    'Deep love endless love flowing like a gentle stream',
    'Khwabon se nikal ke sach ho gaya mera dream',
    '[Guitar solo with lush reverberation]',
    'Hathon mein haath leke chalna hai door talak',
    'Pyaar ka ye roop rahega aasmaan se falak talak',
    'Tujhko hi maana khuda tujhko hi chaha sada',
    'Deep love forevermore stay with me in my soul...',
    '[Soulful fade out with atmospheric beats]'
  ],

  'desi-hum': [
    '[Dhol beats & energetic desi brass trumpet hook]',
    'Desi hum desi mijaaz dil apna bada dildaar',
    'Apni dhun mein jeete hain hum yaaron ke hum yaar',
    'Mitti ki khushboo saanso mein geet hothon pe aabad',
    'Desi rang mein rang gaye sab dhol bajao zoradaar',
    '[Bhangra claps & tumbi high-tempo riff]',
    'Khet khalihaan ki baatein hon ya shehar ki mast galiyaan',
    'Jahaan kadam rakh dein wahaan khilti hain sab kaliyaan',
    'Desi andaaz apna shandaar sabse juda',
    'Apne tevar pe to zamaana bhi ho gaya fida',
    'Chai ki chuski aur yaaron ki mehfil jami rahe',
    'Zindagi ki gaadi pyaar ki patri pe thami rahe',
    '[Dholak roll & syncopated percussion blast]',
    'Apna swad apna thaat desi apna style hai',
    'Har muskuraahat mein dil se aati smile hai',
    'Desi hum desi hain shaan se aao jhoomo re',
    'Zameen se jude hain hum falak ko bhi chhoo lein',
    'Desi hum desi shaan dhol bajao josh se...',
    '[High power Punjabi-Hindi folk crescendo]'
  ],

  'dhuan': [
    '[Dark ambient synthesizer pad & reverb guitar]',
    'Dhuan dhuan hai charo taraf kaisa ye kohra chhaya',
    'Yaadon ki aag sulagti rahi dil ne kisko pukara',
    'Khamoshiyan cheekh rahi hain sannata bole re',
    'Dil ke band darwaze phir kaun aake khole re',
    '[Deep acoustic bass & slow rock drum kit]',
    'Roshni ki talaash mein bhatak raha hai manva',
    'Sawaalon ke jungle mein kho gaya mera aalam',
    'Dhuan dhuan hai raaste khoyi hui manzil',
    'Kisko sunaaye jaake halat-e-bismil',
    'Ummeed ki ek kiran phootegi kabhi to yahaan',
    'Badal jayega ye dhuen ka saara jahaan',
    '[Distorted guitar solo building into emotive peak]',
    'Aansuon se dhul jayenge saare ye gham ke nishan',
    'Naya savera aayega leke naya aasmaan',
    'Dhuan hatega noor barshega iss zameen par',
    'Sabr rakh mere dil ab thodi der thehar',
    'Dhuan dhuan sab chhat jayega ek din...',
    '[Low ambient bass note fading to silence]'
  ],

  'dil-me-chupi': [
    '[Gentle nylon string guitar & soft keyboard pads]',
    'Dil mein chhupi ek baat hai jo hothon pe aati nahi',
    'Teri nigaahon ki meethi chhanv dil se jaati nahi',
    'Kehna chaahun main tujhse par lafz kho jaate hain',
    'Tere aate hi saare gham muskuraate hain',
    '[Upright acoustic bass & brushed snare drum groove]',
    'Chandni raaton mein tera chehra nazar aaye',
    'Hawa ka har jhonka tera hi geet gaaye',
    'Dil mein chhupi mohabbat ab kaise chhupaun',
    'Apne dil ka aalam main kaise bataun',
    'Tu meri manzil tu hi meri subah shaam hai',
    'Meri har dua mein likha bas tera naam hai',
    '[Soulful saxophone solo phrase]',
    'Faaslon ko mita de ek baar kareeb aa ja',
    'Meri sooni zindagi mein bahaar ban ke chha ja',
    'Dil mein chhupi baat ko aaj kehne de zara',
    'Tere bina adhoora tha mera har ek lamha',
    'Dil mein chhupi preet ko tu pehchan le...',
    '[Soft acoustic guitar chords whispering away]'
  ],

  'duniya-ajab-diwani-kabir-tarasingh': [
    '[Santvani Alaap: Tarasingh Dodve singing Sant Kabir]',
    'Duniya ajab diwani re koi ram nam na jaane',
    'Duniya ajab diwani re koi ram nam na jaane',
    'Pathar pooje teerath dole antar aatam bhooli',
    'Duniya ajab diwani re koi ram nam na jaane',
    'Mati ka tan baandha jhootha maya ke bas aani',
    'Char din ka hai mela bhai akhir matti milani',
    '[Ektara & Kartal spiritual rhythmic groove]',
    'Maan barai mein phooli phire lobh moh mein liptaani',
    'Sant milat kachu seekh na leenhi aisi budhi gawaani',
    'Duniya ajab diwani re koi ram nam na jaane',
    'Andha andhe ko rasta dikhave doono kuyein girani',
    'Gyan bina sab bhatak rahe hain kaho kisko samjhani',
    'Kahe kabir suno bhai sadho eka ram dhyana',
    'Naam bina sab kooda karkat chhod moh gumaana',
    'Duniya ajab diwani re santan reet na jaane',
    'Ram naam bhaj le mere manva paar utar kalyani...',
    '[Ektara chord cadence with devotional bow]'
  ],

  'eri-sakhi-main-prem-diwani-tarasingh': [
    '[Soulful Folk Alaap: Sant Meera Bai song by Tarasingh]',
    'Eri sakhi main prem diwani mero dard na jaane koi',
    'Eri sakhi main prem diwani mero dard na jaane koi',
    'Ghaayal ki gat ghaayal jaane jo koi ghaayal hoi',
    'Jauhari ki gat jauhari jaane ki jin jauhar hoi',
    'Eri sakhi main prem diwani mero dard na jaane koi',
    '[Dholak & Manjira sweet devotional swing]',
    'Sooli upar sej hamari kaho kis bidh sona hoi',
    'Gagan mandal pe sej piya ki kis bidh milna hoi',
    'Eri sakhi main prem diwani mero dard na jaane koi',
    'Chot lagi chitt mein aisi aath pehar main royi',
    'Baid bichaara kya kare mera maram na jaane koi',
    'Meera ke prabhu peer mitegi jab baid saawariya hoi',
    'Girdhar laal bina sukh naahi naina neer sanjoyi',
    'Eri sakhi main prem diwani girdhar sang rang royi',
    'Prem diwani Meera bhatke ban ban dhoondhat hoi...',
    '[Kartal and harmonium traditional fade]'
  ],

  'flying-high': [
    '[Upbeat electronic arpeggiator & energetic kick drum]',
    'Chhoo lena hai aasmaan ko khol ke apne baazu',
    'Udd chalein hum baadlon se paar leke naya jadoo',
    'Hawaayein pukarein aaja manzil ko paana hai',
    'Khwabon ki unchi udaan pe jhoom ke gaana hai',
    '[Punchy synth bass & uplifting hook]',
    'Flying high above the mountains flying high into the light',
    'Har darr ko peeche chhod ke chamkeinge we shine bright',
    'Rukna nahi jhukna nahi aage hi aage badhna',
    'Zindagi ke har pahad pe himmat se hai chadhna',
    'Nayi umang nayi tarang dil mein jagi hai',
    'Kamyabi ki roshni ab raahon mein lagi hai',
    '[Guitar shredding solo and dynamic break]',
    'Suraj ki kirno se seekha humne jagmagana',
    'Apne haseen khwabon se naya jahaan banana',
    'Flying high reaching for the stars with all our heart',
    'Jeet ki ye shuruat hai ek pyara sa start',
    'Udd chalein hum uffaq ke paar flying so high...',
    '[Triumphant synth chord finale]'
  ],

  'hum-he-sitare': [
    '[Chorus of children & uplifting acoustic strings]',
    'Hum he sitare aasmaan ke roshni phailaayenge',
    'Andheron ko mita kar hum naya savera laayenge',
    'Sach aur prem ki raahon par kadam apne badhaayenge',
    'Pyar se hum is dharti ko gulshan ek banaayenge',
    '[Flute melody & soft percussion groove]',
    'Phoolon jaisi muskan apni taaron jaisi chhanv',
    'Har dil mein khushiyan baantein jahaan bhi ho apna gaanv',
    'Dada Bhagwan ka sandesh sabko hum sunayenge',
    'Bhed bhaav ko bhula ke hum gale sabhi ko lagayenge',
    'Hum he sitare noor ke hum hain pyare sitare',
    'Satya ahimsa prem se jeeteinge jahaan saare',
    '[Harmonious vocal choir & tubular bells]',
    'Gyan ki jyoti jalakar jeevan safal banayenge',
    'Maitri bhav ki meethi bhasha sabko sikhlayenge',
    'Hum he sitare iss jahaan ke jagmagate sitare',
    'Manavta ke deepak ban kar raahein hum sajayenge...',
    '[Joyous choir fade with chimes]'
  ],

  'jee-le-zara': [
    '[Acoustic strumming & warm pop rock rhythm]',
    'Khule aasmaan ke tale do pal tu jee le zara',
    'Bhoole bisre dukhon ko hans ke tu pee le zara',
    'Subah ki taazi hawa mein meethi si khushboo hai',
    'Tere andar hi chhupa tera apna sukoon hai',
    '[Electric lead guitar riffs with bright tone]',
    'Jee le zara har lamhe ko khushi se saja le',
    'Jo toot gaye the sapne unko phir se bana le',
    'Kyun darrta hai girne se uth ke chalna seekh',
    'Zindagi deti nahi koshish ke bina koi bheed',
    'Doston ka saath ho aur geeton ki bahaar',
    'Phir dekh kaisa lagta hai ye pyara sansaar',
    '[Drum roll & energetic rock guitar breakdown]',
    'Roshni ki talaash mein khud hi tu deepak ban',
    'Bhanwron ki tarah jhoom le chhed naya koi dhan',
    'Jee le zara khul ke muskura dil ki baat sun',
    'Zindagi ek geet hai mast hoke tu gun-gun',
    'Jee le zara mere dost muskura ke jee le zara...',
    '[Uplifting guitar chord resolution]'
  ],

  'kanha-sang-preet-lagi-meera-tarasingh': [
    '[Devotional Alaap: Sant Meera Bai by Tarasingh Dodve]',
    'Kanha sang preet lagi aisi ab to chhuti na chhoote',
    'Kanha sang preet lagi aisi ab to chhuti na chhoote',
    'Lok laaj kul ki marjaada sab jag bhedan toote',
    'Kanha sang preet lagi aisi ab to chhuti na chhoote',
    'Shyam rang mein ranga chunariya prem sindoor sajaayo',
    'Brij ke baasi nand dulaare nainan beech basaayo',
    '[Dholak & Harmonium devotional wave]',
    'Rana bhejyo vish ko pyalo amrit kar pee gayi',
    'Sanwariya ki sharan mein aake Meera nirmal ho gayi',
    'Kanha sang preet lagi aisi ab to chhuti na chhoote',
    'Murali ki madhur taan pe naache man ka mor re',
    'Prem nagari ki saadhvi baandhi preet ki dor re',
    'Meera kahe prabhu girdhar nagar charan saran mein aayi',
    'Bhakti bhav ka daan deejai he karuna ke sain',
    'Kanha sang preet lagi brijmohan nand kishore...',
    '[Devotional manjira crescendo and bow]'
  ],

  'kaya-nagari-me-pardesi-bole-kabir': [
    '[Mystic Santvani Alaap: Sant Kabir Das by Tarasingh Dodve]',
    'Kaya nagari me pardesi bole re manva',
    'Kaya nagari me pardesi bole re manva',
    'Nau darwaze band pare hain daswan khola na jaye',
    'Kaya nagari me pardesi bole re manva',
    'Pinjare ka panchhi ud jayega khali padal rahe pinjra',
    'Matti ka tan matti mein milega dhoondhat phire bahaana',
    '[Ektara twang & Dholak Nirgun rhythm]',
    'Kaya nagari ka bhed nirala santan birle jaane',
    'Shabd roopi tir chalaya satguru ne man maane',
    'Kaya nagari me pardesi bole re manva',
    'Gyan ki kothari khol ke dekh le andar basat murari',
    'Baahar bhatkat umar bitaayi antar deep jalaari',
    'Kahat kabir suno bhai sadho eka roop pehchano',
    'Aatam ram sada sukhdayi nirmal hridaya maano',
    'Kaya nagari me pardesi bole ram ram chit dhyano...',
    '[Meditative ektara note dying out]'
  ],

  'kya-hove-re-nahaye-dhoye-kabir': [
    '[Philosophical Kabir Alaap: Tarasingh Dodve]',
    'Kya hove re nahaye dhoye jab man ka mail na jaaye',
    'Kya hove re nahaye dhoye jab man ka mail na jaaye',
    'Meen sada jal mein hi rahe par sugandh kahan se paaye',
    'Kya hove re nahaye dhoye jab man ka mail na jaaye',
    'Teerath nahaaye kashi gaye ganga snan kareene',
    'Antar kapat rakhe man maahin gyan na kachu seekheene',
    '[Kartal & Folk Dholak lively Nirgun beat]',
    'Maala phiri tilak lagaya bahar bhekh banaya',
    'Hridaya shuddh bhayo nahi tab tak saheb haath na aaya',
    'Kya hove re nahaye dhoye jab man ka mail na jaaye',
    'Kaam krodh mada moh ko tyaago prem rasayan peeo',
    'Satya bachan hridaya mein dharo jeevan saarthak jeeo',
    'Kahat kabir suno bhai sadho nirmal man jo hove',
    'Taahi ko gobind milat hai gyan ka moti boye',
    'Kya hove re nahaye dhoye man ko shuddh bana re...',
    '[Traditional Santvani folk finale]'
  ],

  'maayi-ri-maine-liyo-govindo-mol-tarasingh': [
    '[Ecstatic Bhakti Alaap: Meera Bai by Tarasingh Dodve]',
    'Maayi ri maine liyo govindo mol maayi ri maine liyo govindo mol',
    'Koi kahe sasto koi kahe mehngo liyo re taraaju tol',
    'Maayi ri maine liyo govindo mol maayi ri maine liyo govindo mol',
    'Koi kahe chhane koi kahe chhupke liyo ri bajanta dhol',
    'Maayi ri maine liyo govindo mol maayi ri maine liyo govindo mol',
    'Koi kahe kaalo koi kahe goro liyo re amolak mol',
    '[Manjira rhythmic flourishes & harmonium run]',
    'Jaaku sabhi shanka karat the maine aankh ughol',
    'Maayi ri maine liyo govindo mol giridhari lala mol',
    'Tan diyo man diyo sees diyo saaro deeno prem anmol',
    'Meera ke prabhu girdhar nagar purab janam ko qaul',
    'Maayi ri maine liyo govindo mol maayi ri maine liyo govindo mol',
    'Charan kamal ki aash lagayi kripa karo braj chhol',
    'Govinda gopal mukunda Meera hridaya khol',
    'Maayi ri maine liyo govindo mol liyo bajanta dhol...',
    '[Devotional joyous temple rhythm outro]'
  ],

  'more-to-giridhar-gopala-dusro-na-koi-mss': [
    '[Iconic Carnatic-Hindustani Alaap: M. S. Subbulakshmi in Raga Mishra Kafi]',
    'More to giridhar gopala dusro na koi',
    'More to giridhar gopala dusro na koi',
    'Jaake sir mor mukut mero pati soi',
    'More to giridhar gopala dusro na koi',
    'Taat maat bhrat bandhu aapno na koi',
    'Chhaand dayi kul ki kaan ka karihai koi',
    '[Veena Gamakas & Mridangam soft theka]',
    'Santan sang baithi baithi lok laaj khoi',
    'Asuwan jal seench seench prem beli boi',
    'More to giridhar gopala dusro na koi',
    'Ab to bel phail gayi aanand phal hoi',
    'Bhagati dekhi raazi bhayi jagat dekhi royi',
    'Daasi meera laal giridhar taaro ab mohi',
    'More to giridhar gopala dusro na koi',
    'Girdhar nagar prabhu avinashi charan kamal chitt joi',
    'More to giridhar gopala dusro na koi pyaro nand kishore...',
    '[M. S. Subbulakshmi divine tanpura resonance fade]'
  ],

  'musafir-jana-padega-re-manva-kabir': [
    '[Solemn Nirguni Alaap: Sant Kabir by Tarasingh Dodve]',
    'Musafir jana padega re manva dhar le ram ka dhyan',
    'Musafir jana padega re manva dhar le ram ka dhyan',
    'Ye jag rain basera pyare koi na rahe yahaan nishaan',
    'Musafir jana padega re manva dhar le ram ka dhyan',
    'Kodi kodi maya jodi baandh na sakyo gathari',
    'Ant samay sab chhoot jayega khali haath chaloge nagari',
    '[Ektara & gentle Dholak introspective beat]',
    'Matti ka tan banaya maalik kripa kari anmol',
    'Bhakti bina sab beetho gawaayo jhoothe vishay mein dol',
    'Musafir jana padega re manva dhar le ram ka dhyan',
    'Jinki khatir paap kamaye sang na chale koi bhai',
    'Dharm karma hi saath nibhaave dhar har naam sahaye',
    'Kahat kabir suno bhai sadho chet sake to chet',
    'Nirbhay ho ke bhajo hari naam chhoot jaye bhav khet',
    'Musafir jana padega re manva satguru sharan pehchaan...',
    '[Deep resonance fading into solemn silence]'
  ],

  'na-jane-tera-saheb-kaisa-hai-kabir': [
    '[Deep Inquisitive Santvani: Sant Kabir by Tarasingh Dodve]',
    'Na jaane tera saheb kaisa hai re bande',
    'Na jaane tera saheb kaisa hai re bande',
    'Mandir masjid dhoondhat dole antar ki na sojhe',
    'Na jaane tera saheb kaisa hai re bande',
    'Pahan pooje hari mile to main poojun pahaad',
    'Ghar ki chaaki koi na pooje pees khaaye sansaar',
    '[Kartal & Sarangi melodic phrases]',
    'Jal mein kumbh kumbh mein jal hai bahar bheetar paani',
    'Phoota kumbh jal jal hi samaana kaho kisan gyaani',
    'Na jaane tera saheb kaisa hai re bande',
    'Kasturi kundal base mrig dhoondhat ban maahi',
    'Aise ghat ghat ram hain duniya dekhe naahi',
    'Kahe kabir suno bhai sadho bhed bharam sab kholo',
    'Ghat mein viraje saheb pyara prem se ram bolo',
    'Na jaane tera saheb kaisa hai antar khoj manva...',
    '[Kartal cadence with meditative tanpura]'
  ],

  'nirgun-bhajan-kumar-gandharva-kabir': [
    '[Aalap: Pandit Kumar Gandharva in monumental Malwa Kabir Nirgun style]',
    'Avadhoota yugan yugan hum yogi avadhoota yugan yugan hum yogi',
    'Aave na jaave mite na kabahu sabad anaahad bhogi',
    'Avadhoota yugan yugan hum yogi avadhoota yugan yugan hum yogi',
    'Sab rang roop se nyaara aatam nirmal jyoti anokhi',
    'Shunya shikar par anhad baaje amrit ki dhun chokhi',
    '[Intense Harmonium & Pakhawaj classic Malwa rhythm]',
    'Surati niraati ki dori baandhi pawan palat ghari laayi',
    'Ida pingala sukhman naadi triveni sangam bhaayi',
    'Avadhoota yugan yugan hum yogi avadhoota yugan yugan hum yogi',
    'Na hum kaashi na hum kaaba na hum jogi janta',
    'Ek akhand niranjan gaavein param purush ananta',
    'Kahe kabir suno ho avadhoo gagan mandal mein dhyana',
    'Ghat ghat mein jo jyoti jage hai soi purush pradhaana',
    'Avadhoota yugan yugan hum yogi param tattva anuraagi',
    'Nirgun nirakar avinashi satchidanand vihaari...',
    '[Monumental Kumar Gandharva crescendo & tanpura peace]'
  ],

  'payoji-maine-ram-ratan': [
    '[Reverent Harmonium Prelude: Sant Meera Bai by Sujay Govindaraj]',
    'Payoji maine ram ratan dhan payo payoji maine ram ratan dhan payo',
    'Vastu amolik di mere satguru kirpa kar apnaayo',
    'Payoji maine ram ratan dhan payo payoji maine ram ratan dhan payo',
    'Janam janam ki poonji paayi jag mein sabhi khovaayo',
    'Payoji maine ram ratan dhan payo payoji maine ram ratan dhan payo',
    'Kharach na khootai chor na lootai din din badhat savaayo',
    '[Flute & Tabla classical Keherwa beat]',
    'Sat ki naav khevatiya satguru bhavsagar tar aayo',
    'Payoji maine ram ratan dhan payo payoji maine ram ratan dhan payo',
    'Meera ke prabhu giridhar naagar harakh harakh jas gaayo',
    'Charan kamal par sees navaun anand mangal paayo',
    'Bhakti sudha ras ghol piyayo prem patang udayo',
    'Payoji maine ram ratan dhan payo shree ram ratan dhan payo',
    'He giridhari he banwari nitya hi mangal chaayo',
    'Payoji maine ram ratan dhan payo ram ratan dhan payo...',
    '[Sweet devotional tabla tehai & flute finale]'
  ],

  'raghupati-raghav-raja-ram': [
    '[Bhakti Alaap: Hari Om Sharan soulful devotional classic]',
    'Raghupati raghav raja ram patita pavan sita ram',
    'Raghupati raghav raja ram patita pavan sita ram',
    'Sita ram sita ram bhaja pyare tu sita ram',
    'Raghupati raghav raja ram patita pavan sita ram',
    'Ishwar allah tero naam sabko sanmati de bhagwan',
    'Raghupati raghav raja ram patita pavan sita ram',
    '[Harmonium & Dholak sweet spiritual rhythm]',
    'Kaushalya ke nandan ram janaki vishram ram',
    'Dasharath nandan deen dayal he raghuveer kripal',
    'Raghupati raghav raja ram patita pavan sita ram',
    'Prem mudit man se kaho ram ram sita ram',
    'Paap taap sab door bhagaye ram naam sukhdhaam',
    'Shree ram jai ram jai jai ram karuna sindhu sita ram',
    'Mangala bhavana amangala haari dravahu sudasharath ajira bihari',
    'Raghupati raghav raja ram patita pavan sita ram...',
    '[Hari Om Sharan harmonious devotional chorus fade]'
  ],

  'rana-ji-tharo-deshadlo-rang-roodo-tarasingh': [
    '[Rajasthani Folk Bhakti Alaap: Meera Bai by Tarasingh Dodve]',
    'Rana ji tharo deshadlo rang roodo re',
    'Rana ji tharo deshadlo rang roodo par mhare gobind gungan gaavun',
    'Rana ji tharo deshadlo rang roodo re',
    'Mahal mehal thare kanch ke bangla heere moti ki thali',
    'Mhane bhaye kadam ki chhaiyan mhane bhaye bansi wali',
    'Rana ji tharo deshadlo rang roodo re',
    '[Rajasthani Dholak & Khartal traditional swing]',
    'Rana ji bhejiye vish ka pyalo Meera hans hans peevan laagi',
    'Girdhar laal ki aisi kripa thi amrit ras mein bhagi',
    'Rana ji tharo deshadlo rang roodo re',
    'Na mhane chaahiye raj path tharo na mhane heere heera',
    'Girdhar nagar charan kamal mein leen rahe man meera',
    'Rana ji tharo deshadlo chhod chalun mhaari gobind nagari aayi',
    'Braj ki raahon mein chhanan chhanan ghunghroo baandh naachi',
    'Rana ji tharo deshadlo rang roodo girdhari sang laagi...',
    '[Joyous folk kartal finale with devotional cry]'
  ],

  'sakhiya-wah-ghar-sabse-niyara-kabir': [
    '[Deep Contemplative Alaap: Pandit Kumar Gandharva singing Kabir]',
    'Sakhiya wah ghar sabse nyaara jahan pooran purush hamaara',
    'Sakhiya wah ghar sabse nyaara jahan pooran purush hamaara',
    'Jahan nahi dhoop chhanv nahi baadal nahi taara na taara',
    'Sakhiya wah ghar sabse nyaara jahan pooran purush hamaara',
    'Nahi tahin chand na suraj chamke nahi tahin andhiyara',
    'Soham shabda anhad baaje amrit ki jhar jhara',
    '[Harmonium drone & majestic Pakhawaj strokes]',
    'Kaal karam jahan vyape nahi naahi kshudha trishna dhara',
    'Param pad par baithe saheb sachchidanand ujiyara',
    'Sakhiya wah ghar sabse nyaara jahan pooran purush hamaara',
    'Bina bajaaye baansuri baaje bina baje jhankaara',
    'Kahe kabir suno bhai sadho gagan mandal te nyaara',
    'Jo jan uss ghar ko pehchaane soi paar utaara',
    'Sakhiya wah ghar sabse nyaara purush anant apaara...',
    '[Sublime Kumar Gandharva vocal decay and tanpura silence]'
  ],

  'ye-mausam': [
    '[Acoustic guitar intro & breeze sound effect]',
    'Ye mausam hai mastana ye rutt hai suhani',
    'Hawaayein sunati hain ek nayi kahani',
    'Patte bhi jhoomein phool bhi muskuraayein',
    'Aao hum dono milke nayi dhun banayein',
    '[Upbeat pop drums & electric piano keys]',
    'Ye mausam suhana kahe dil ki baatein',
    'Bheegi si subahein haseen aisi raatein',
    'Chalte chalein hum unhi raaston par',
    'Jahan pyaar barse zameen aasmaan par',
    'Khwabon ke rangon mein rang li nigahein',
    'Pukaarein humein ab to nayi nayi raahein',
    '[Sweet flute interlude & rhythmic claps]',
    'Mausam ka jaadu hai charo taraf chhaya',
    'Dil ne sukoon ka ye lamha hai paaya',
    'Gungunaye fizayein gaaye ye mausam',
    'Saath tera ho to khushiyan hain hardam',
    'Ye mausam suhana rahe sada yun hi...',
    '[Warm acoustic fade with gentle bird chirps]'
  ]
};
