// Master Authentic Bengali Lyrics for all 48 Bengali songs in Talent5
// Romanized English transliteration for pure vocal singing along

export const BENGALI_LYRICS = {
  "aamar-e-poth-tomar-pather-biporite": [
    "[Esraj & harmonium prelude: Rabindra Sangeet in Raga Pilu]",
    "Aamar e poth tomar pather theke onek dure",
    "Aamar e poth tomar pather theke onek dure",
    "Aami jani aamar e gaan tomar hridoy chhunye jaabe",
    "Kobe kon shondhay tumi aamay daakbe aapon shure",
    "Aamar e poth tomar pather theke onek dure",
    "[Acoustic sitar & tabla vilambit dadra interlude]",
    "Chhaya ghonay baner pothe nishi jaage aakash paane",
    "Aamar moner akul bhabona bhese jaay ogo kon gaane",
    "Tumi aacho aapon mone ami achhi aapon ashay",
    "Aamar e poth tomar pather theke onek dure",
    "Kobe hobe milon aamar e shure tomar o shure...",
    "[Esraj gentle evening fade]"
  ],
  "aamar-ke-nibi-bhai": [
    "[Brisk folk-classical Rabindra Sangeet in Baul rhythm]",
    "Aamar ke nibi bhai shonpbo aamay apon mone",
    "Aamar ke nibi bhai shonpbo aamay apon mone",
    "Ami beche achhi mukto batase e dharar e anonde",
    "Aamar ke nibi bhai shonpbo aamay apon mone",
    "[Dotara & ektara lively Baul strumming]",
    "Dhaner kshete shonali ronge aalo jholmol kore",
    "Nodi boye jaay ogo chirokaal aapon chhande chhande",
    "Aamar ke nibi bhai shonpbo aamay apon mone...",
    "[Ektara cheerful fade]"
  ],
  "aamar-prabhat-madhur-holo-tomar-parash": [
    "[Bhairavi sunrise overture: Rabindranath Tagore]",
    "Aamar prabhat madhur holo tomar aalor porosh peye",
    "Aamar prabhat madhur holo tomar aalor porosh peye",
    "Noyon mela hridoy khola aaji jugol chokhe cheye",
    "Aamar prabhat madhur holo tomar aalor porosh peye",
    "[Sweet bansuri & harmonium sunrise melody]",
    "Phuler mukhe haasi phutechhe pakhi gaay gaan bhorer baay",
    "Chiro sundor chiro anondo aaji dharay neme aay",
    "Aamar prabhat madhur holo tomar o gaan geye...",
    "[Bhairavi morning peace fade]"
  ],
  "aar-nai-re-bela-tagore-rabindra": [
    "[Evening pathos in Raga Purvi: Rabindranath Tagore]",
    "Aar nai re bela aakashe megh jomechhe ghor",
    "Aar nai re bela aakashe megh jomechhe ghor",
    "Apon pothe phire cholo aaji neme aashe andhar",
    "Aar nai re bela aakashe megh jomechhe ghor",
    "[Esraj lingering meend & soft tabla]",
    "Nodir jole dhew uthechhe batash bohe dheere",
    "Ogo shathi kothay aachho aay re aapon teere",
    "Aar nai re bela aakashe megh jomechhe ghor...",
    "[Purvi solemn fade]"
  ],
  "abak-prithibi-abak-korle-tumi": [
    "[Sukanta Bhattacharya revolutionary anthem by Salil Chowdhury]",
    "Abak prithibi abak korle tumi jonme e deshe",
    "Abak prithibi abak korle tumi jonme e deshe",
    "Muktir gaan gaibo aamra nuton aalor beshe",
    "Abak prithibi abak korle tumi jonme e deshe",
    "[Orchestral violins & driving march rhythm]",
    "Shikol bhangar gaan je baaje aaji ghore ghore",
    "Muktir suryo uthbe ebar aamader e bhore",
    "Abak prithibi abak korle tumi nuton aalor deshe...",
    "[Triumphant chorus crescendo]"
  ],
  "adhora-madhuri": [
    "[Rabindra Sangeet in Raga Kafi: Melodic romance]",
    "Adhora madhuri dhorechhe je aaji aamar e praane",
    "Adhora madhuri dhorechhe je aaji aamar e praane",
    "Chokher samne shundor roop bhese othe kon gaane",
    "Adhora madhuri dhorechhe je aaji aamar e praane",
    "[Sitar & flute delicate romantic dialogue]",
    "Bhalobashar e prohor jeno chirokaal e thake",
    "Hridoy aaji shob hariye apon kore daake",
    "Adhora madhuri dhorechhe je chiro moner majhe...",
    "[Sitar sweet resolution]"
  ],
  "aguner-poroshmoni-chhowao-prane-tagore": [
    "[Rabindranath Tagore prayer of divine purification]",
    "Aguner poroshmoni chhonwao praane",
    "Aguner poroshmoni chhonwao praane",
    "E jibon punyo koro daaho daaho daaho daaho daaho daaho",
    "Aguner poroshmoni chhonwao praane",
    "[Solemn Esraj & tanpura resonance]",
    "Shokol dukh malinota jalao shokol jalao praane",
    "Aalokmoy koro aamar hridoy e dharar majhe",
    "Aguner poroshmoni chhonwao praane chiro aalor gaane...",
    "[Peaceful Esraj spiritual fade]"
  ],
  "aha-aji-e-boshanto-rabindranath-tagore": [
    "[Joyous springtime Rabindra Sangeet: Rabindranath Tagore]",
    "Aha aji e boshanto koto phul phote koto banshi baaje",
    "Aha aji e boshanto koto phul phote koto banshi baaje",
    "Koto kokil gaay gaan koto aalo jhole baner majhe",
    "Aha aji e boshanto koto phul phote koto banshi baaje",
    "[Joyful bansuri & tabla dadra rhythm]",
    "Moner aashay nupur baaje anonder e melay",
    "Palaash phuler ronge ronge hriday dolay dolay",
    "Aha aji e boshanto koto phul phote aaji shobhar majhe...",
    "[Springtime celebratory coda]"
  ],
  "aj-rate-ghumiye-porona-hemanta": [
    "[Intimate nocturnal Rabindra Sangeet]",
    "Aj rate ghumiye porona shathi aaro kothao aachhe shur",
    "Aj rate ghumiye porona shathi aaro kothao aachhe shur",
    "Jochhona jhore purnima rate akash bhora aalote",
    "Aj rate ghumiye porona shathi aaro kothao aachhe shur",
    "[Harmonium & acoustic guitar quiet night melody]",
    "Chander aaloy nodir dhare bose aamra geye jaai",
    "Hridoy jure bhalobashar e gaan geye shob paai",
    "Aj rate ghumiye porona priyo aaro kotha shuni...",
    "[Nocturnal peaceful fade]"
  ],
  "aloo-amar-aloo-ogo-rabindra": [
    "[Celebration of divine light: Rabindranath Tagore]",
    "Aloo amar aloo ogo aloo bhubon bhora",
    "Aloo amar aloo ogo aloo bhubon bhora",
    "Aloo noyon dhoa amar aloo hridoy hora",
    "Nache aalo nache ogo patae patae nache",
    "Aloo amar aloo ogo aloo bhubon bhora",
    "[Vibrant Rabindra Sangeet rhythm with tabla and dholak]",
    "Batash bohe chhonno chhara shundorer e majhe",
    "Surjyo othe purno theje jagot jage haashe",
    "Pran khule aaji gaan gai chiro aalor pothe",
    "Aloo amar aloo ogo shokol dukh harani",
    "Anando dhara jochhona jhore dhonye holo dhara",
    "Aloo amar aloo ogo parama mangalamoye...",
    "[Joyous vocal cadence and flute finale]"
  ],
  "amar-mon-manena-dinorojoni-tagore": [
    "[Rabindranath Tagore in Raga Yaman Kalyan]",
    "Amar mon manena dinorojoni amar mon manena",
    "Amar mon manena dinorojoni amar mon manena",
    "Aami kothay jabo kaar kache rabo keno e byakulata",
    "Amar mon manena dinorojoni amar mon manena",
    "[Sitar & Esraj sweet longing melody]",
    "Hridoy majhe aaji jeno apon keu daake",
    "Ami bhese choli shure shure taari apon baake",
    "Amar mon manena chiro shather aashay...",
    "[Sitar fading chord]"
  ],
  "amar-pothe-pothe-pathor-tagore-promit": [
    "[Philosophical resilience: Rabindranath Tagore]",
    "Amar pothe pothe pathor chhorano aami tai to thomke darai",
    "Amar pothe pothe pathor chhorano aami tai to thomke darai",
    "Tobu aami haar manbo na aapon pothe jabo egiye",
    "Amar pothe pothe pathor chhorano aami tai to thomke darai",
    "[Esraj intense phrases and strong tabla beat]",
    "Dukh joto aashe aamaye shokti diye jaay chirokaal",
    "Aapon shottie aami pabo nuton prabhat bhorer aaloy",
    "Amar pothe pothe pathor chhorano tobu pothe choli...",
    "[Determined cadence]"
  ],
  "amare-karo-jeebon-daan-tagore-suchitra": [
    "[Rabindranath Tagore profound prayer]",
    "Amare karo jeebon daan he chiro sundoro",
    "Amare karo jeebon daan he chiro sundoro",
    "Apon premey dhonyo karo aamar e mon praan",
    "Amare karo jeebon daan he chiro sundoro",
    "[Harmonium & sitar solemn progression]",
    "Shokol bipod shokol voy thakuk aamar theke dure",
    "Tomar kripay shob peyechhi chiro anondo pure",
    "Amare karo jeebon daan he parama shantimoy...",
    "[Spiritual peaceful closure]"
  ],
  "ami-hridoyer-katha-bolite-byakul-tagore": [
    "[Rabindranath Tagore emotional confession]",
    "Ami hridoyer katha bolite byakul apon moner majhe",
    "Ami hridoyer katha bolite byakul apon moner majhe",
    "Ke shonabe aamay gaan kotha je aaji baaje",
    "Ami hridoyer katha bolite byakul apon moner majhe",
    "[Sweet violin & flute gentle interlude]",
    "Bhalobashar e bhabona gopone rekhechhi aami",
    "Kobe kon dine hobe shob katha je naami",
    "Ami hridoyer katha bolite byakul chiro sathiye...",
    "[Violin emotional fade]"
  ],
  "ami-keboli-swapon-korechhi-bopon-tagore": [
    "[Rabindranath Tagore in Raga Kafi]",
    "Ami keboli swapon korechhi bopon aakash bhora meghe",
    "Ami keboli swapon korechhi bopon aakash bhora meghe",
    "Shei swapone aaji aamar mon je jaage ektu aalor aashay",
    "Ami keboli swapon korechhi bopon aakash bhora meghe",
    "[Sitar sweet flourishes & soft rhythm]",
    "Phuler mukhe haasi phute swapno holo sothyi",
    "Chiro kaal dhori aaji aamra geye jaai mukti",
    "Ami keboli swapon korechhi bopon shundor e dharay...",
    "[Sitar peaceful fade]"
  ],
  "ami-tumar-preme-hobo-bhikari-tagore": [
    "[Rabindranath Tagore devotional surrender]",
    "Ami tumar preme hobo bhikari chirokaal apon mone",
    "Ami tumar preme hobo bhikari chirokaal apon mone",
    "Tomar charane shonpbo aamay dhonye hobo e jibone",
    "Ami tumar preme hobo bhikari chirokaal apon mone",
    "[Esraj & harmonium profound melody]",
    "Dhon doulot kichhu chai na aami shudhu chai tomar sneho",
    "Apon premey aamay ghire raakho ogo chiro shundoro",
    "Ami tumar preme hobo bhikari he parama bandhu...",
    "[Esraj peaceful fade]"
  ],
  "anandaloke-mangalaloke": [
    "[Rabindranath Tagore universal Vedic anthem]",
    "Anandaloke mangalaloke birajo satyo sundoro",
    "Anandaloke mangalaloke birajo satyo sundoro",
    "Sobhita sundoro aakash jure shanti birajomano",
    "Anandaloke mangalaloke birajo satyo sundoro",
    "[Grand choral harmony & harmonium majesty]",
    "Chandro suryo graha tara chirokaal gaaye tomar shur",
    "Bhubone bhubone jage aaji muktir shundor shur",
    "Anandaloke mangalaloke birajo satyo sundoro jaya...",
    "[Grand choral coda]"
  ],
  "bandhu-michhe-raag-koro-na-tagore": [
    "[Playful romantic Rabindra Sangeet]",
    "Bandhu michhe raag koro na apon mone shathi",
    "Bandhu michhe raag koro na apon mone shathi",
    "Aamra duto manush aaji purno korbo rati",
    "Bandhu michhe raag koro na apon mone shathi",
    "[Flute & tabla playful kaharwa groove]",
    "Haasi mukhe cheye dekho aakash koto shundor",
    "Raag bhule aaji bhalobasho aamader e mon",
    "Bandhu michhe raag koro na aay re aamader ghore...",
    "[Flute cheerful fade]"
  ],
  "basante-ki-shudhu": [
    "[Poignant Rabindra Sangeet in Raga Bhairavi]",
    "Basante ki shudhu phuler milon hoye moner milon noy",
    "Basante ki shudhu phuler milon hoye moner milon noy",
    "Hridoy kotha kobe phute uthbe aamar e dhoronoy",
    "Basante ki shudhu phuler milon hoye moner milon noy",
    "[Bhairavi meend & sitar taan]",
    "Kokiler e gaan shune aaji praane jage aasha",
    "Chirokaal jeno thake aamader e bhalobasha",
    "Basante ki shudhu phuler milon noy moner milon hoye...",
    "[Bhairavi gentle resolution]"
  ],
  "bhalobashi-bhalobashi-ei-sure-kache": [
    "[Beloved Rabindra Sangeet hymn of cosmic love]",
    "Bhalobashi bhalobashi e shur baje aamar praane",
    "Bhalobashi bhalobashi e shur baje aamar praane",
    "Aakashe batase e gaan bhese jaay ogo kon gaane",
    "Bhalobashi bhalobashi e shur baje aamar praane",
    "[Violin & Esraj sweet resonant confluence]",
    "Nodir jole chhayay chhayay aaji dekhi aapon mukh",
    "Shokol shrishti bhalobashay bheshe gechhe purno sukh",
    "Bhalobashi bhalobashi e shur chirokaal baaje...",
    "[Sweet violin fade out]"
  ],
  "bhalobeshe-sakhi-nivrite-tagore-chinmoy": [
    "[Intimate lyrical confession: Rabindranath Tagore]",
    "Bhalobeshe sakhi nivrite joton koro aamar e mon",
    "Bhalobeshe sakhi nivrite joton koro aamar e mon",
    "Gopone rekho aamaye tomar hridoyer gopon kon",
    "Bhalobeshe sakhi nivrite joton koro aamar e mon",
    "[Acoustic guitar & bansuri gentle pacing]",
    "Kotha bolona kaaro shathe shudhu cheye dekho aamaye",
    "Chiro jibon shathe robe e bhalobashar chhayay",
    "Bhalobeshe sakhi nivrite rekho aamar e praan...",
    "[Acoustic guitar fading notes]"
  ],
  "charano-dharite-diyogo-amare": [
    "[Hemanta Mukhopadhyay master vocal: Rabindra Sangeet]",
    "Charano dharite diyogo amare nio na nio na shoraye",
    "Charano dharite diyogo amare nio na nio na shoraye",
    "Bandhibo amare tomaro charane chiro bhalobashar e doraye",
    "Charano dharite diyogo amare nio na nio na shoraye",
    "[Esraj & harmonium soaring classical taans]",
    "Shokol abhimaan shokol ohorongkar jaaliye diilam praane",
    "Tomar daake hridoy amaar shob haralo doole kon gaane",
    "Apon kore nio amare he chiro bandhu chiro ashray",
    "Charano dharite diyogo amare nio na nio na shoraye...",
    "[Esraj deep emotional resolution]"
  ],
  "dakbona-dakbona-aar-tomare-tagore": [
    "[Rabindra Sangeet in Raga Purvi]",
    "Dakbona dakbona aar tomare aami mukto korlam aaji",
    "Dakbona dakbona aar tomare aami mukto korlam aaji",
    "Apon pothe tumi jao chole jodi na aashe aaji raji",
    "Dakbona dakbona aar tomare aami mukto korlam aaji",
    "[Sitar quiet reflective strokes]",
    "Tobu aamar moner majhe roye jabe tomar e chhabi",
    "Chiro shundor chiro sathiye aapon kore bhabi",
    "Dakbona dakbona aar tomare apon shure thakbo...",
    "[Sitar gentle fade]"
  ],
  "daya-diye-hobe-tomay": [
    "[Rabindranath Tagore spiritual submission]",
    "Daya diye hobe tomay aapon kore nite",
    "Daya diye hobe tomay aapon kore nite",
    "Aamar dosh truti shob kshama kore dite",
    "Daya diye hobe tomay aapon kore nite",
    "[Harmonium & tanpura solemn progression]",
    "Ami obujh ami deeno aamar kichhu nei",
    "Tomar kripay shob pabo he prabhu shob ei",
    "Daya diye hobe tomay apon kore nite he shorono...",
    "[Harmonium peaceful fade]"
  ],
  "dekhate-pare-ne-keno": [
    "[Rabindra Sangeet in Raga Kafi]",
    "Dekhate pare ne keno moner majhe joto bhabona chhilam",
    "Dekhate pare ne keno moner majhe joto bhabona chhilam",
    "Kotha chhilam bolite kintu gopone shob rekhe dilam",
    "Dekhate pare ne keno moner majhe joto bhabona chhilam",
    "[Flute sweet melancholy phrases]",
    "Kobe bujhbe aamar e hridoyer koto bhalobasha",
    "Aaji aakash jure jage aamader e nuton aasha",
    "Dekhate pare ne keno moner kotha chiro din...",
    "[Flute gentle fade]"
  ],
  "dhwanilo-ahabano-madhuro": [
    "[Rabindranath Tagore inspiring call of awakening]",
    "Dhwanilo ahabano madhuro gondhe aakash holo purno",
    "Dhwanilo ahabano madhuro gondhe aakash holo purno",
    "Jagot jage nuton aaloy shokol dukh churno",
    "Dhwanilo ahabano madhuro gondhe aakash holo purno",
    "[Grand Esraj & tabla rhythm]",
    "Muktir gaan gaibo aamra aaji shobhar majhe",
    "Chiro shundor chiro anondo hridoye aaji baaje",
    "Dhwanilo ahabano madhuro e bhorer e pothe...",
    "[Joyous finale]"
  ],
  "e-bela-dak-porechhe": [
    "[Rabindra Sangeet in Raga Bhairav]",
    "E bela dak porechhe aapon pothe jete hobe ebar",
    "E bela dak porechhe aapon pothe jete hobe ebar",
    "Somoy holo shob cheye aapon ghorer daak ebar",
    "E bela dak porechhe aapon pothe jete hobe ebar",
    "[Esraj morning classical alaap]",
    "Chiro shathi aamaye daake parama shantir pothe",
    "Ami choli apon mone aalor rath er rothe",
    "E bela dak porechhe chiro aalor deshe jete...",
    "[Bhairav serene fade]"
  ],
  "ebar-amai-dakle-priyo-rabindra": [
    "[Serene Esraj and harmonium Rabindra Sangeet prelude]",
    "Ebar amai dakle priyo dakle bujhi phire apon mone",
    "Ebar amai dakle priyo dakle bujhi phire apon mone",
    "Ami jabo nodir teere shondha belar theere aalor pothe",
    "Aakash jure meghe meghe rongeer khela hoye shundor kore",
    "Ebar amai dakle priyo dakle bujhi phire apon mone",
    "[Gentle acoustic guitar and sitar interlude]",
    "Moner majhe gaan jage aaji akul byakule taari daake",
    "Tomar daake hridoy amaar shob haralo doole kon baake",
    "Chiro jibon shathe robe ogo chiro bandhu he priyotomo",
    "Ebar amai dakle priyo apon kore nebe e jibone",
    "Shanto rateer chaand uthechhe nirmolo aalote bhubon jure",
    "Ebar amai dakle priyo he chiro sundoro aay re...",
    "[Melodious Esraj fade out into the evening silence]"
  ],
  "ei-maumachhider-ghar-chhara": [
    "[Pramita Mallick springtime Rabindra Sangeet]",
    "Ei maumachhider ghar chhara gaan baaje aaji banantore",
    "Ei maumachhider ghar chhara gaan baaje aaji banantore",
    "Phule phule modhu khonje madhur boshonto aaji jhore",
    "Ei maumachhider ghar chhara gaan baaje aaji banantore",
    "[Playful dotara & flute rhythm]",
    "Batash aaji bhese jaay modhuro gondhe anonde",
    "Aamra nachbo aamra gaibo nuton e chhande",
    "Ei maumachhider ghar chhara gaan baaje chiro kaal...",
    "[Dotara lively fade]"
  ],
  "ekla-cholo-re": [
    "[Iconic Rabindranath Tagore anthem of courage]",
    "Jodi tor dak shune keu na ashe tobe ekla cholo re",
    "Jodi tor dak shune keu na ashe tobe ekla cholo re",
    "Ekla cholo ekla cholo ekla cholo ekla cholo re",
    "Jodi tor dak shune keu na ashe tobe ekla cholo re",
    "[Stirring acoustic guitar & harmonium march rhythm]",
    "Jodi keu katha na koy orey orey o abhagya",
    "Jodi shobai thake mukh phiraye shobai kore bhoy",
    "Tobe paran khule tui mukh phute tor moner katha ekla bolo re",
    "Jodi tor dak shune keu na ashe tobe ekla cholo re",
    "Jodi shobai phire jaay orey orey o obhaga",
    "Jodi poth er baje aandhar jome aagun tui jala",
    "Tobey bajroanole apon buker paajor jaliey niye ekla jolo re",
    "Jodi tor dak shune keu na ashe tobe ekla cholo re...",
    "[Resolute, defiant marching cadence and guitar strum]"
  ],
  "he-nutan": [
    "[Rabindranath Tagore birthday hymn of rebirth]",
    "He nutan dekha dao aar-bar jonmer pratham shubha-khone",
    "He nutan dekha dao aar-bar jonmer pratham shubha-khone",
    "Kuashar buke theke neme esho aalor joyo-gane",
    "He nutan dekha dao aar-bar jonmer pratham shubha-khone",
    "[Grand orchestral strings & solemn conch sound]",
    "Chiro chiro sundor chiro anonde bheshe uthuk dhora",
    "Aamader e jibon aaji hok nuton aloy bhora",
    "He nutan dekha dao aaji e bhorer e pothe...",
    "[Majestic sunrise fanfare]"
  ],
  "jakhon-porbe-na": [
    "[Immortal farewell Rabindra Sangeet: Rabindranath Tagore]",
    "Jakhon porbe na mor payer chinho ei baate",
    "Jakhon porbe na mor payer chinho ei baate",
    "Ami baibo na mor kheyatoroni ei ghaate",
    "Jakhon porbe na mor payer chinho ei baate",
    "[Soulful Esraj & acoustic guitar progression]",
    "Chuke jaabe mor becha-kena mitta jaabe shob paona dena",
    "Tobu aamar e gaan thakbe bheshe tomar e praane",
    "Kobe kon shondhay tumi aamaye mone porbe kon gaane",
    "Jakhon porbe na mor payer chinho tobu aami roye jabo...",
    "[Esraj lingering emotional fade]"
  ],
  "je-chhilo-amar-swapone-charini-tagore": [
    "[Dreamy romantic Rabindra Sangeet in Raga Pilu]",
    "Je chhilo amar swapone charini taare dekhi aaji e aakash majhe",
    "Je chhilo amar swapone charini taare dekhi aaji e aakash majhe",
    "Hridoy majhe taari shur chirokaal e baaje",
    "Je chhilo amar swapone charini taare dekhi aaji e aakash majhe",
    "[Sitar & flute delicate Pilu meend]",
    "Bhalobashar e prohor jeno chiro thake aamader ghore",
    "Aapon kore pelam taare aaji bhorer e aalote",
    "Je chhilo amar swapone charini shei aamar chiro sathi...",
    "[Sitar romantic fade]"
  ],
  "je-dhrubho-je-dhrubho-rabindra-sangeet": [
    "[Gautam Mitra classical Rabindra Sangeet]",
    "Je dhrubho je dhrubho aakashe taara hoye jaage",
    "Je dhrubho je dhrubho aakashe taara hoye jaage",
    "Taari shur aamar hridoye baje chiro shundor bhaabe",
    "Je dhrubho je dhrubho aakashe taara hoye jaage",
    "[Esraj & tabla classical vilambit rhythm]",
    "Chiro shorono aamaye daake aalor e pothe",
    "Ami choli apon mone shanti rath er rothe",
    "Je dhrubho je dhrubho taari charane shonpi aaji...",
    "[Esraj profound resolution]"
  ],
  "khama-karo-more-shakhi-tagore": [
    "[Rabindranath Tagore gentle apology to companion]",
    "Khama karo more shakhi apon bhul er tore",
    "Khama karo more shakhi apon bhul er tore",
    "Jodi kokhono aami dukh diye thaki tomaare",
    "Khama karo more shakhi apon bhul er tore",
    "[Sweet harmonium & acoustic violin]",
    "Aamader e bhalobasha chirokaal thakbe aamader majhe",
    "Aay re aamra geye jaai nuton anonder e gaane",
    "Khama karo more shakhi aay re bhalobashar ghore...",
    "[Violin sweet fade]"
  ],
  "mono-jago-mangalaloke-rabindra-sangeet": [
    "[Promit Sen sacred Rabindra Sangeet prayer]",
    "Mono jago mangalaloke birajo satyo shundoro aaji",
    "Mono jago mangalaloke birajo satyo shundoro aaji",
    "Aalokmoy koro aamar hridoy e prabhat e raaji",
    "Mono jago mangalaloke birajo satyo shundoro aaji",
    "[Solemn classical organ & harmonium chords]",
    "Shokol dukh shokol voy jaak e dharar theke",
    "Chiro anonde jeno bheshe uthi aamra shobai kripay",
    "Mono jago mangalaloke he parama bandhu...",
    "[Sacred choral fade]"
  ],
  "mor-prabhater-ei-aarati": [
    "[Morning aarati: Rabindranath Tagore in Raga Bhairav]",
    "Mor prabhater ei aarati shompilam tomar charane",
    "Mor prabhater ei aarati shompilam tomar charane",
    "Surjyer aaloy phul er gondhey aaji pujilam tomai",
    "Mor prabhater ei aarati shompilam tomar charane",
    "[Temple bells & sweet bansuri sunrise melody]",
    "Hridoyer shob bhabona aaji tomay shonpi aami",
    "Chirokaal apon snehey dhonyo koro he naami",
    "Mor prabhater ei aarati he parama shundoro...",
    "[Auspicious sunrise fade]"
  ],
  "mor-veena": [
    "[Rabindranath Tagore song of musical dedication]",
    "Mor veena aaji kon shure baaje apon mone",
    "Mor veena aaji kon shure baaje apon mone",
    "Kobe kon shondhay tumi aamaye daakbe aapon shure",
    "Mor veena aaji kon shure baaje apon mone",
    "[Classical Veena & sitar strumming]",
    "Sapta swarer madhurye aaji hridoy bhore gelo",
    "Tomar premer e aalote shob aadhar kete gelo",
    "Mor veena aaji tomar e gaan geye thakbe...",
    "[Veena lingering notes]"
  ],
  "na-chahile-jare-paoa-jay-tagore-hemanta": [
    "[Rabindranath Tagore philosophical masterpiece]",
    "Na chahile jare paoa jay taare keno aamra bujhi na",
    "Na chahile jare paoa jay taare keno aamra bujhi na",
    "Apon kripay jini neme aashe taare keno khunji na",
    "Na chahile jare paoa jay taare keno aamra bujhi na",
    "[Esraj & sitar contemplative progression]",
    "Batash jemon aapon theke shobai ke chhunye jaay",
    "Suryer aalo jemon kore dhoronir mukh chhay",
    "Shei to aamader chiro ashray taare keno bhabi na...",
    "[Philosophical peaceful closure]"
  ],
  "nayan-tomare-pay": [
    "[Nilima Sen in Raga Kafi: Rabindra Sangeet]",
    "Nayan tomare pay na dekhite royechho nayane nayane",
    "Nayan tomare pay na dekhite royechho nayane nayane",
    "Hridoy tomare pay na jaanite royechho gopon mone",
    "Nayan tomare pay na dekhite royechho nayane nayane",
    "[Sweet Esraj taan & soft tabla]",
    "Aapon aloy aapon chhobite tumi to aacho shob jaaygay",
    "Ami obujh tai to tomaye khunji aakasher taray taray",
    "Nayan tomare pay na dekhite tobu tumi chiro shathi...",
    "[Esraj lingering fade]"
  ],
  "nutan-juger-bhore-suchitra-mitra": [
    "[Suchitra Mitra rousing dawn anthem of the new era]",
    "Nutan juger bhore aamra nuton gaan gaibo aaji",
    "Nutan juger bhore aamra nuton gaan gaibo aaji",
    "Shikol bhangar shobder shathe muktir shur e raaji",
    "Nutan juger bhore aamra nuton gaan gaibo aaji",
    "[Driving march rhythm & brass accompaniment]",
    "Dharar shokol manush aaji pabe aapon odhikar",
    "Chiro shundor chiro anonde bhorbe e sansar",
    "Nutan juger bhore aay re aamra egiye jabo...",
    "[Triumphant chorus finale]"
  ],
  "nuton-pran-dao-he-nirmolo-anonde": [
    "[Anusaruti Mitra prayer for new life and vitality]",
    "Nuton pran dao he prabhu nuton aasha dao aamaye",
    "Nuton pran dao he prabhu nuton aasha dao aamaye",
    "Aamader e dharay jeno aashe nuton anondo chhayay",
    "Nuton pran dao he prabhu nuton aasha dao aamaye",
    "[Harmonium & sitar majestic spiritual alaap]",
    "Shokol klanti shokol andhar dur kore dao aaji",
    "Tomar kripay purno hok aamader e kaaj e raaji",
    "Nuton pran dao he chiro shundoro parama bandhu...",
    "[Spiritual grand resolution]"
  ],
  "o-ki-elo-re-priyatama-tagore": [
    "[Joyous arrival Rabindra Sangeet in Raga Kafi]",
    "O ki elo o ki elo re priyatama aamader e ghore",
    "O ki elo o ki elo re priyatama aamader e ghore",
    "Aakash batash aaji bhese gelo anonder e jhore",
    "O ki elo o ki elo re priyatama aamader e ghore",
    "[Flute & tabla lively dadra groove]",
    "Phuler mala gathbo aamra shundor kore aaji",
    "Priyar mukhe haasi dekhe hridoy uthlo raaji",
    "O ki elo o ki elo re priyatama aay re bhalobashay...",
    "[Flute festive coda]"
  ],
  "sakhi-bohe-gelo-bela-rabindranath": [
    "[Poignant lyrical evening song: Rabindranath Tagore]",
    "Sakhi bohe gelo bela shonona aamar e katha",
    "Sakhi bohe gelo bela shonona aamar e katha",
    "Hridoy majhe aaji jeno jomechhe koto byatha",
    "Sakhi bohe gelo bela shonona aamar e katha",
    "[Melodic Esraj & sitar dialog]",
    "Shondha neme aashlo dharay pakhi phire taar baashay",
    "Ami eka bose achhi taari pather aashay",
    "Sakhi bohe gelo bela tobu mone aasha aachhe...",
    "[Esraj gentle evening fade]"
  ],
  "sansaro-jabe-monoharveshe": [
    "[Nilima Sen in Raga Yaman: Rabindra Sangeet]",
    "Sansaro jabe monoharveshe aapon aaloy jaage",
    "Sansaro jabe monoharveshe aapon aaloy jaage",
    "Hridoy majhe taari shur chiro shundor bhaabe laage",
    "Sansaro jabe monoharveshe aapon aaloy jaage",
    "[Yaman classical swaram with Esraj]",
    "Shokol dukh bhule aaji bheshe jaabo anonde",
    "Tomar premer e gane chiro nuton e chhande",
    "Sansaro jabe monoharveshe apon shure thakbo...",
    "[Yaman serene closure]"
  ],
  "sukhe-amar-rakhbe-keno-tagore": [
    "[Philosophical Rabindra Sangeet on growth through sorrow]",
    "Sukhe amar rakhbe keno dukh dao he aamaye",
    "Sukhe amar rakhbe keno dukh dao he aamaye",
    "Dukh er majhe jeno aami khunje pai tomaye",
    "Sukhe amar rakhbe keno dukh dao he aamaye",
    "[Esraj intense soulful phrases]",
    "Shokol aagoon shokol aaghat aamaye goruk nuton bhabe",
    "Tomar charane jeno aami shob shonpi anonde",
    "Sukhe amar rakhbe keno dukh e tomai paabo...",
    "[Esraj meditative fade]"
  ],
  "tomar-dekha-pabo-bole-tagore-suchitra": [
    "[Beloved Rabindra Sangeet: Longing for the Divine]",
    "Tomar dekha pabo bole aami pothe pothe ghuri",
    "Tomar dekha pabo bole aami pothe pothe ghuri",
    "Kobe kon shondhay tumi aamay daakbe shundor kuri",
    "Tomar dekha pabo bole aami pothe pothe ghuri",
    "[Acoustic sitar & bansuri romantic longing]",
    "Phuler gandhey aakasher rong ey tomaye khunji aami",
    "Apon hridoye bosho ogo chiro shundor chiro naami",
    "Tomar dekha pabo bole chirokaal kaadiruve...",
    "[Sitar peaceful resolution]"
  ],
  "tomay-gaan-shonabo-tagore-debabrata": [
    "[Beloved lyrical pledge: Rabindranath Tagore]",
    "Tomay gaan shonabo tai to aami aaji ekhane elam",
    "Tomay gaan shonabo tai to aami aaji ekhane elam",
    "Hridoyer shob bhabona aaji tomay shonpi dilam",
    "Tomay gaan shonabo tai to aami aaji ekhane elam",
    "[Sweet Esraj & acoustic guitar harmony]",
    "Kotha chhilam bolite je gopon chhilam moner majhe",
    "Tomar daake hridoy amaar shur e shur e aaji baaje",
    "Tomay gaan shonabo chiro jibon apon shathe...",
    "[Esraj sweet final chord]"
  ]
};
